# Generated by Django 3.2.18 on 2023-07-07 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20230707_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='watchlist',
            field=models.ManyToManyField(default=None, null=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
