# Generated by Django 3.2.18 on 2023-07-07 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20230707_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='authored', to=settings.AUTH_USER_MODEL),
        ),
    ]
