# Generated by Django 3.2.18 on 2023-07-08 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20230708_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auctionlisting'),
            preserve_default=False,
        ),
    ]
